#!/bin/sh
#
# This script downloads the Freescale Yocto Community BSP release and adds
# the F&S layer to it.

source ./yocto-f+s-utilities

# Cause script to stop on errors, e.g. if download fails
set -e

# Download the repo tool that handles the download of several GIT repos
if [ ! -x ./repo ]
then
    echo "Downloading repo tool"
    curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > repo
    chmod a+x repo
fi

# Download the Freescale Release BSP repo description for DIZZY
echo "Getting download information (repo init)"
DOWNLOAD_URL=https://source.codeaurora.org/external/imx/imx-manifest
BRANCH=imx-linux-zeus
MANIFEST=imx-5.4.70-2.3.2.xml
./repo init -u $DOWNLOAD_URL -b $BRANCH -m $MANIFEST

# Download the GIT repositories. This is:
#  - fsl-community-bsp-base
#  - meta-fsl-arm
#  - meta-fsl-arm-extra
#  - meta-fsl-demos
#  - meta-fsl-bsp-release
#  - meta-browser
#  - meta-qt5
#  - poky
#  - meta-openembedded
echo "Downloading all Yocto packages (repo sync)"
./repo sync

# Download mono layer
DOWNLOAD_URL=http://git.yoctoproject.org/cgit/cgit.cgi/meta-mono
BRANCH=zeus
git clone $DOWNLOAD_URL sources/meta-mono -b $BRANCH

# Download murata layer and modify it
./murata-download

# Remove link to fsl-setup-release.sh as it is called directly in
# fus-setup-release.sh
rm imx-setup-release.sh

# Print user manual form yocto-f+s-utilities
print_usage
